# -*- coding: utf-8 -*-
"""crompressor_lab14_llama.ipynb

Automatically generated by Colaboratory.

# 🦙 CROM Lab14: KV Cache Compression em LLaMA-7B
**Objetivo**: Validar a tese de compressão extrema do KV Cache (>90%) usando Vector Quantization em modelos >1B params, medindo o impacto real na perplexity.

**Hardware recomendado**: T4 GPU (Google Colab Free)
"""

# @title Instalação de Dependências
# !pip install -q transformers accelerate bitsandbytes sentencepiece
# !pip install -q scikit-learn

import torch
import torch.nn as nn
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from sklearn.cluster import KMeans, MiniBatchKMeans
import numpy as np
import json
import time
import math
import os

print(f"CUDA Available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"Device: {torch.cuda.get_device_name(0)}")

"""## 1. Carregar Modelo 4-bit (LLaMA-7B / Mistral-7B)"""

# Podemos usar o Mistral v0.1 caso o LLaMA precise de aprovação (gated)
MODEL_ID = "mistralai/Mistral-7B-v0.1" # Substitua por meta-llama/Llama-2-7b-hf se preferir

print(f"Carregando {MODEL_ID} em 4-bit...")

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)

print("Modelo carregado com sucesso.")

"""## 2. Extração do KV Cache Original"""

def get_kv_cache(prompt, max_tokens=256):
    """Roda o modelo num prompt e captura o past_key_values."""
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    
    with torch.no_grad():
        # Apenas forward pass preenchendo o cache
        outputs = model(**inputs, use_cache=True)
    
    kv_cache = outputs.past_key_values
    
    # 1. Tupla nativa (versões velhas)
    if isinstance(kv_cache, tuple):
        return kv_cache
        
    # 2. Iterável (suporte __iter__ no DynamicCache v4.38+)
    try:
        extracted = list(kv_cache)
        if len(extracted) > 0 and isinstance(extracted[0], tuple):
            return tuple(extracted)
    except Exception:
        pass
        
    # 3. Método oficial de conversão
    if hasattr(kv_cache, "to_legacy_cache"):
        try:
            legacy = kv_cache.to_legacy_cache()
            if isinstance(legacy, tuple):
                return legacy
        except Exception:
            pass
            
    # 4. Nuclear Option: introspecção direta no __dict__ do objeto
    keys, values = [], []
    for attr, val in kv_cache.__dict__.items():
        # Busca por listas de tensores (que representam as camadas)
        if isinstance(val, list) and len(val) > 0 and isinstance(val[0], torch.Tensor):
            if 'key' in attr.lower() or 'k_cache' in attr.lower():
                keys = val
            elif 'value' in attr.lower() or 'v_cache' in attr.lower():
                values = val
                
    if len(keys) > 0 and len(keys) == len(values):
        return tuple(zip(keys, values))
        
    raise ValueError(f"Blindagem de extração falhou. Atributos ocultos: {kv_cache.__dict__.keys()}")

prompt = """
O futuro da compressão neural não está em reduzir os pesos do modelo, mas sim em comprimir o contexto.
O KV Cache é o principal gargalo de memória na inferência de LLMs. Se conseguirmos quantizar os tensores
de Key e Value usando um Codebook não-linear, podemos atingir taxas de compressão muito além do limite de Shannon
para bits discretos. A pesquisa0 provou 94.2% em GPT-2. Agora vamos testar a escala.
""" * 3 # Aumentar o contexto

start_time = time.time()
original_kv = get_kv_cache(prompt)
print(f"Extração KV Cache: {time.time() - start_time:.2f}s")

# Analisando o shape
num_layers = len(original_kv)
sample_k = original_kv[0][0]
batch, heads, seq_len, head_dim = sample_k.shape
print(f"Layers: {num_layers}")
print(f"Shape K/V: (batch={batch}, heads={heads}, seq={seq_len}, dim={head_dim})")

total_elements = num_layers * 2 * batch * heads * seq_len * head_dim
original_bytes = total_elements * 2 # float16 = 2 bytes
print(f"Tamanho Original (apenas este prompt): {original_bytes / 1024 / 1024:.2f} MB")

"""## 3. Vector Quantization (Codebook Learning)"""

def quantize_tensor_vq(tensor, k=256):
    """Aplica K-Means VQ num tensor 4D do KV Cache."""
    # tensor shape: (batch, heads, seq, dim)
    b, h, s, d = tensor.shape
    
    # Achatar para 2D: (batch*heads*seq, dim)
    flat_tensor = tensor.reshape(-1, d).float().cpu().numpy()
    
    # Treinar Codebook
    kmeans = MiniBatchKMeans(n_clusters=k, random_state=42, batch_size=1024, n_init=3)
    labels = kmeans.fit_predict(flat_tensor)
    
    # Reconstruir tensor quantizado
    centroids = kmeans.cluster_centers_
    quantized_flat = centroids[labels]
    
    # Voltar para shape e device originais
    quantized_tensor = torch.tensor(quantized_flat, dtype=tensor.dtype, device=tensor.device)
    quantized_tensor = quantized_tensor.reshape(b, h, s, d)
    
    # Calcular compressão
    # Tamanho original: N * d * 2 bytes (fp16)
    # Codebook: K * d * 2 bytes + N * (log2(K)/8) bytes (indices)
    orig_bytes = flat_tensor.shape[0] * d * 2
    codebook_bytes = k * d * 2
    
    # 256 = 1 byte per index (8 bits)
    # 65536 = 2 bytes per index (16 bits)
    bytes_per_idx = math.ceil(math.log2(k)/8)
    indices_bytes = flat_tensor.shape[0] * bytes_per_idx
    
    comp_bytes = codebook_bytes + indices_bytes
    ratio = 1.0 - (comp_bytes / orig_bytes)
    
    return quantized_tensor, ratio, comp_bytes

print("Quantizando KV Cache (isto pode demorar 1-2 mins)...")
K_CLUSTERS = 256

quantized_kv = []
total_orig_bytes = original_bytes
total_comp_bytes = 0

start_time = time.time()
for layer_idx, (k_tensor, v_tensor) in enumerate(original_kv):
    if layer_idx % 4 == 0:
        print(f"Quantizando layer {layer_idx}/{num_layers}...")
        
    q_k, ratio_k, b_k = quantize_tensor_vq(k_tensor, k=K_CLUSTERS)
    q_v, ratio_v, b_v = quantize_tensor_vq(v_tensor, k=K_CLUSTERS)
    
    quantized_kv.append((q_k, q_v))
    total_comp_bytes += (b_k + b_v)

print(f"Tempo de Quantização: {time.time() - start_time:.2f}s")
print(f"Tamanho Comprimido: {total_comp_bytes / 1024 / 1024:.2f} MB")
print(f"Taxa de Compressão: {(1.0 - (total_comp_bytes/total_orig_bytes)) * 100:.2f}%")

"""## 4. Medição de Perplexity (Impacto de Qualidade)"""

def calculate_perplexity(model, input_ids, past_key_values=None):
    """Calcula a perplexity do texto (lower is better)."""
    with torch.no_grad():
        if past_key_values is None:
            outputs = model(input_ids, labels=input_ids)
        else:
            # Temos que passar context+1 no passado? Para medir perplexity com KV injetado
            # É complexo injetar todo o KV num único forward. 
            # Aproximação: medir loss dos logits reconstruídos
            pass
            
        return math.exp(outputs.loss.item())

# Para medir perplexity COM o KV cache quantizado, a forma mais robusta é injetar o KV customizado
# e gerar tokens. Mas a perplexity padrão do HuggingFace (labels=input_ids) ignora past_key_values.
# Em vez disso, vamos medir a Cosine Similarity entre a predição original e a quantizada no token final!

def compare_logits(prompt, kv_original, kv_quantized):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    
    # O prompt tem seq_len tokens. O KV Cache tem seq_len. 
    # Queremos gerar o token seq_len+1 usando o Cache e passando apenas o ÚLTIMO token como input
    last_token = inputs.input_ids[:, -1:]
    
    # Suporte para converter tupla legacy de volta para DynamicCache
    def prepare_cache(legacy_kv):
        try:
            from transformers.cache_utils import DynamicCache
            new_cache = DynamicCache()
            for layer_idx, (k, v) in enumerate(legacy_kv):
                new_cache.update(k, v, layer_idx)
            return new_cache
        except ImportError:
            # Versão antiga do Transformers não tem DynamicCache
            return legacy_kv
        
    kv_orig_obj = prepare_cache(kv_original)
    kv_quant_obj = prepare_cache(kv_quantized)
    
    with torch.no_grad():
        out_orig = model(last_token, past_key_values=kv_orig_obj)
        logits_orig = out_orig.logits[:, -1, :]
        
        out_quant = model(last_token, past_key_values=kv_quant_obj)
        logits_quant = out_quant.logits[:, -1, :]
    
    # Cosine Similarity dos logits (como a distribuição de probabilidade foi afetada)
    cos_sim = nn.functional.cosine_similarity(logits_orig, logits_quant).item()
    
    # L2 Error (MSE)
    mse = nn.functional.mse_loss(logits_orig, logits_quant).item()
    
    # KL Divergence entre as distribuições (Softmax)
    prob_orig = nn.functional.softmax(logits_orig, dim=-1)
    log_prob_quant = nn.functional.log_softmax(logits_quant, dim=-1)
    kl_div = nn.functional.kl_div(log_prob_quant, prob_orig, reduction='batchmean').item()
    
    return cos_sim, mse, kl_div

print("Avaliando impacto nas predições (Logits Similarity)...")
cos_sim, mse, kl_div = compare_logits(prompt, original_kv, quantized_kv)

print(f"Cosine Similarity (1.0 = idêntico): {cos_sim:.4f}")
print(f"KL Divergence (0.0 = idêntico)  : {kl_div:.4f}")

"""## 5. Salvar Resultados"""

result = {
    "model": MODEL_ID,
    "context_tokens": seq_len,
    "k_clusters": K_CLUSTERS,
    "metrics": {
        "original_mb": total_orig_bytes / 1024 / 1024,
        "compressed_mb": total_comp_bytes / 1024 / 1024,
        "compression_pct": (1.0 - (total_comp_bytes/total_orig_bytes)) * 100,
        "cosine_similarity": cos_sim,
        "kl_divergence": kl_div,
        "mse": mse
    }
}

print(json.dumps(result, indent=2))

with open("lab14_results.json", "w") as f:
    json.dump(result, f, indent=2)

print("\nConcluído! Faça o download de lab14_results.json")
